//select all the elements
let selectfile=document.querySelector('#selectfile')
let preview=document.querySelector('#previewim')
let postbtn=document.querySelector('#submitbtn')
let imgsec=document.querySelector('.imgsec')
let photobtn =document.querySelector('#photobtn')

//first add the evnt  lstener to the photo button
photobtn.addEventListener('click',()=>{
//after havng click on it un hid eit 
selectfile.style.display='block'

})
selectfile.addEventListener("change",(event)=>{
const file = event.target.files[0] //lock the file 


postbtn.addEventListener('click',()=>{
// when click to the post button 

 if(file){ //if file is selected 
       const reader=new FileReader()// read the file 
       reader.onload=function(e){// onload(event)  after loading the file read it  
        const imgcon=document.createElement("div")// then create a div 
       
        //dynamic css styling
        imgcon.style.padding="10px"
        imgcon.style.height="150px"
        imgcon.style.width="300px"
//dynamically creating  the image 
        const img=document.createElement('img')
        // Set the source of the image element to the Data URL generated by the FileReader.
// This allows the browser to display the selected image.
        img.src=e.target.result 
        img.style.height="100%"
        img.style.width="100%"
        img.style.positon="relative";
        img.style.objectFit="cover"
      imgsec.appendChild(imgcon) 
       imgcon.appendChild(img)
       }
     reader.readAsDataURL(file)
}
})
})