FROM node:18-alpine
#createing working directory for app
WORKDIR /app
#coping pakage.json and pakage lock json 
COPY package*.json ./
# install other depends..
RUN npm install
#copy the rest code form directory
COPY . .
# after finshing executeb the script 
CMD ["node", "service.js"]
